# Generated by Django 3.1.3 on 2020-12-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201231_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, choices=[('Genel', 'Genel'), ('Kediler', 'Kediler'), ('Köpekler', 'Köpekler'), ('Hamsterlar', 'Hamsterlar'), ('Sürüngenler', 'Sürüngenler')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post/image/'),
        ),
    ]
